import { parseDocument } from 'yaml';
import type { BackupRule } from './types.js';

interface RuleDocument {
  version?: number;
  claw_type?: string;
  created_at?: string;
  source_dir?: string;
  backup_dir?: string;
  restore_dir?: string;
  include?: string[];
  exclude?: string[];
}

export function serializeRule(rule: BackupRule, options?: { includeComment?: string }): string {
  const comments = [
    'Generated by beaver-claw-backup.',
    'Edit include/exclude paths before running backup if needed.',
    options?.includeComment,
  ]
    .filter(Boolean)
    .map((line) => `# ${line}`);

  const formatScalar = (value: string | number): string => {
    if (typeof value === 'number') {
      return String(value);
    }
    return JSON.stringify(value);
  };

  const formatList = (values: string[]): string => {
    if (values.length === 0) {
      return '[]';
    }
    return `\n${values.map((value) => `  - ${JSON.stringify(value)}`).join('\n')}`;
  };

  const lines = [
    ...comments,
    `version: ${formatScalar(rule.version)}`,
    `claw_type: ${formatScalar(rule.clawType)}`,
    `created_at: ${formatScalar(rule.createdAt)}`,
    `source_dir: ${formatScalar(rule.sourceDir)}`,
    `backup_dir: ${formatScalar(rule.backupDir)}`,
    `restore_dir: ${formatScalar(rule.restoreDir)}`,
    `include: ${formatList(rule.include)}`,
    `exclude: ${formatList(rule.exclude)}`,
  ];

  return `${lines.join('\n')}\n`;
}

export function parseRuleYaml(raw: string): BackupRule {
  const parsed = parseDocument(raw).toJS() as RuleDocument | null;
  if (!parsed || typeof parsed !== 'object') {
    throw new Error('Rule file does not contain a YAML object.');
  }

  const requiredKeys: Array<keyof RuleDocument> = [
    'version',
    'claw_type',
    'created_at',
    'source_dir',
    'backup_dir',
    'restore_dir',
    'include',
    'exclude',
  ];
  for (const key of requiredKeys) {
    if (parsed[key] === undefined) {
      throw new Error(`Missing "${key}" in rule file.`);
    }
  }

  if (
    !Array.isArray(parsed.include) ||
    !parsed.include.every((value) => typeof value === 'string')
  ) {
    throw new Error('Rule field "include" must be a list of strings.');
  }
  if (
    !Array.isArray(parsed.exclude) ||
    !parsed.exclude.every((value) => typeof value === 'string')
  ) {
    throw new Error('Rule field "exclude" must be a list of strings.');
  }

  return {
    version: Number(parsed.version),
    clawType: String(parsed.claw_type),
    createdAt: String(parsed.created_at),
    sourceDir: String(parsed.source_dir),
    backupDir: String(parsed.backup_dir),
    restoreDir: String(parsed.restore_dir),
    include: parsed.include,
    exclude: parsed.exclude,
  };
}
